
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
import guiLanding
# Explicit imports to satisfy Flake8



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


# window = Tk()

# window.geometry("1200x800")
# window.configure(bg = "#FFFFFF")

class GenerateKey(Frame):
    def __init__(self, master):
        Frame.__init__(self, master, width = 1200, height = 800, bg = "#FFFFFF")
        self.canvas = Canvas(
            master,
            bg = "#FFFFFF",
            height = 800,
            width = 1200,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.canvas.create_text(
            217.0,
            42.0,
            anchor="nw",
            text="Generate Public Key and Private Key",
            fill="#28293D",
            font=("Poppins SemiBold", 42 * -1)
        )

        self.canvas.create_text(
            95.0,
            128.65501403808594,
            anchor="nw",
            text="p Value",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.canvas.create_text(
            95.0,
            235.93190002441406,
            anchor="nw",
            text="q Value",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.canvas.create_text(
            557.0,
            361.50390625,
            anchor="nw",
            text="Result",
            fill="#28293D",
            font=("OpenSansRoman Bold", 26 * -1)
        )

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            600.0,
            189.0,
            image=self.entry_image_1
        )
        self.entry_1 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=111.63205909729004,
            y=164.0,
            width=976.7358818054199,
            height=48.0
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            600.0,
            303.0,
            image=self.entry_image_2
        )
        self.entry_2 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=111.63205909729004,
            y=278.0,
            width=976.7358818054199,
            height=48.0
        )

        self.canvas.create_text(
            95.0,
            411.400146484375,
            anchor="nw",
            text="Public Key",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.canvas.create_text(
            95.0,
            518.6768798828125,
            anchor="nw",
            text="Private Key",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            600.0,
            472.0,
            image=self.entry_image_3
        )
        self.entry_3 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=111.63205909729004,
            y=447.0,
            width=976.7358818054199,
            height=48.0
        )

        self.entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        self.entry_bg_4 = self.canvas.create_image(
            600.0,
            586.0,
            image=self.entry_image_4
        )
        self.entry_4 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_4.place(
            x=111.63205909729004,
            y=561.0,
            width=976.7358818054199,
            height=48.0
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiLanding.Landing),
            relief="flat"
        )
        self.button_1.place(
            x=618.8326416015625,
            y=695.80810546875,
            width=216.11448669433594,
            height=68.19168090820312
        )

        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiLanding.Landing),
            relief="flat"
        )
        self.button_2.place(
            x=366.0,
            y=695.80810546875,
            width=216.11444091796875,
            height=68.19168090820312
        )