
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
import guiLanding

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class Verify(Frame):
    def __init__(self, master):
        Frame.__init__(self, master, width = 1200, height = 800, bg = "#FFFFFF")
        self.canvas = Canvas(
            master,
            bg = "#FFFFFF",
            height = 800,
            width = 1200,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            600.0,
            495.0,
            image=self.entry_image_1
        )
        self.entry_1 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=111.86170387268066,
            y=447.0,
            width=976.2765922546387,
            height=94.0
        )

        self.canvas.create_text(
            319.999755859375,
            40.0,
            anchor="nw",
            text="Verifying Digital Signature",
            fill="#28293D",
            font=("Poppins SemiBold", 42 * -1)
        )

        self.canvas.create_text(
            95.0,
            126.837646484375,
            anchor="nw",
            text="Public Key",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.canvas.create_text(
            95.0,
            235.5958251953125,
            anchor="nw",
            text="Message/File",
            fill="#000000",
            font=("OpenSansRoman Regular", 20 * -1)
        )

        self.canvas.create_text(
            556.0,
            373.0185546875,
            anchor="nw",
            text="Result",
            fill="#28293D",
            font=("OpenSansRoman Bold", 26 * -1)
        )

        self.canvas.create_text(
            452.0,
            475.8748779296875,
            anchor="nw",
            text="Verified or Unverified",
            fill="#28293D",
            font=("OpenSansRoman Bold", 26 * -1)
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            600.0,
            188.5,
            image=self.entry_image_2
        )
        self.entry_2 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=111.86170387268066,
            y=163.0,
            width=976.2765922546387,
            height=49.0
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            600.0,
            304.0,
            image=self.entry_image_3
        )
        self.entry_3 = Text(
            bd=0,
            bg="#D9E4E8",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=111.86170387268066,
            y=279.0,
            width=976.2765922546387,
            height=48.0
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiLanding.Landing),
            relief="flat"
        )
        self.button_1.place(
            x=490.0,
            y=701.8212890625,
            width=219.0986328125,
            height=69.13302612304688
        )

        self.canvas.create_rectangle(
            1057.0,
            177.0,
            1081.71484375,
            199.99998474121094,
            fill="#000000",
            outline="")

        self.canvas.create_rectangle(
            1057.0,
            292.0,
            1081.71484375,
            314.99999237060547,
            fill="#000000",
            outline="")
